project_id = "qwmgzbgcpypwjenchfei"

[functions.create-election]
verify_jwt = true

[functions.polish-proposal]
verify_jwt = true

[functions.generate-proposal-description]
verify_jwt = true

[functions.generate-proposal-illustration]
verify_jwt = true

[functions.og-meta-handler]
verify_jwt = false