project_id = "qwmgzbgcpypwjenchfei"

[functions.create-election]
verify_jwt = true

[functions.generate-election-tags]
verify_jwt = false

[functions.polish-proposal]
verify_jwt = true

[functions.generate-proposal-description]
verify_jwt = true

[functions.generate-proposal-illustration]
verify_jwt = true

[functions.check-voter-eligibility]
verify_jwt = false